name: Dummy

on:
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  # See 'ci/README.md' at the repository root for more details.
  merge-checks-buildkite:
    runs-on: ubuntu-latest
    if: github.repository == 'RouterBase/tensorzero'
    steps:
      - run: echo "This is a dummy job to satisfy branch protection checks"
